server:
  port: 8888

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ibinsigma/springcloud-config-repository.git

          search-paths:
            - configuration/{application}/
            - configuration/

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8721/eureka/